# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push, pull_request]

jobs:
    build:
        name: Build and Test
        runs-on: ubuntu-latest
        # See image content at https://github.com/actions/virtual-environments/blob/ffa2110464ecda1cc62b477f29609525de24e570/images/linux/Ubuntu1804-README.md
        env:
            NODE_ENV: test
            CC: gcc-6
            CXX: g++-6
            FORCE_COLOR: true
            TOKEN: ${{ secrets.TOKEN }}

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x, 15.x, 16.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Test on Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
